<?php
declare(strict_types=1);
require __DIR__.'/../src/ExternalMonitorCore.php';
require __DIR__.'/../src/ExternalMonitorAdapter.php';
use ControlBot\Observability\ExternalMonitorAdapter;use ControlBot\Observability\ExternalMonitorCore;

function adapter(callable $http,?callable $alert=null): ExternalMonitorAdapter{return new ExternalMonitorAdapter($http,$alert??fn(array $p)=>['status'=>'delivered','code'=>'accepted']);}
function req(): array{return ['version'=>1,'endpoint_kind'=>'health','url'=>'https://control.example.com/health','observed_at'=>1000,'timeout_ms'=>1000,'max_redirects'=>1,'max_body_bytes'=>2048,'source_ref'=>'controlbot:probe'];}
function down(): array{$p=ExternalMonitorCore::probe(['version'=>1,'endpoint_kind'=>'health','observed_at'=>1000,'outcome'=>'timeout','http_status'=>null,'latency_ms'=>1000,'reported_version'=>null,'reported_sha'=>null,'freshness'=>'fresh','source_ref'=>'controlbot:probe']);return ExternalMonitorCore::assess($p,[],null,1000,300);}
function healthy(): array{$p=ExternalMonitorCore::probe(['version'=>1,'endpoint_kind'=>'health','observed_at'=>1000,'outcome'=>'response','http_status'=>200,'latency_ms'=>20,'reported_version'=>'1.2.3','reported_sha'=>str_repeat('a',40),'freshness'=>'fresh','source_ref'=>'controlbot:probe']);return ExternalMonitorCore::assess($p,[],null,1000,300);}
$case=$argv[1]??'';
if($case==='probe'){$a=adapter(fn($d)=>['outcome'=>'response','http_status'=>200,'latency_ms'=>20,'body'=>json_encode(['version'=>'1.2.3','sha'=>str_repeat('a',40)]),'redirects'=>0]);echo json_encode($a->probe(req()),JSON_THROW_ON_ERROR),PHP_EOL;exit;}
if($case==='failures'){$a=adapter(fn($d)=>['outcome'=>'timeout','http_status'=>null,'latency_ms'=>999,'body'=>'','redirects'=>0]);$timeout=$a->probe(req());$b=adapter(fn($d)=>['outcome'=>'response','http_status'=>500,'latency_ms'=>30,'body'=>'password=never-output','redirects'=>0]);$server=$b->probe(req());echo json_encode(['timeout'=>$timeout,'server'=>$server],JSON_THROW_ON_ERROR),PHP_EOL;exit;}
if($case==='deliver'){$calls=0;$a=adapter(fn($d)=>[],function($p)use(&$calls){$calls++;return ['status'=>'delivered','code'=>'accepted'];});$sent=$a->deliver(down(),['version'=>1,'channel'=>'webhook','observed_at'=>1001,'evidence_ref'=>'controlbot:alert']);$quiet=$a->deliver(healthy(),['version'=>1,'channel'=>'webhook','observed_at'=>1001,'evidence_ref'=>'controlbot:alert']);echo json_encode(['sent'=>$sent,'quiet'=>$quiet,'calls'=>$calls],JSON_THROW_ON_ERROR),PHP_EOL;exit;}
if($case==='channel_fail'){$a=adapter(fn($d)=>[],fn($p)=>['status'=>'failed','code'=>'webhook_timeout']);echo json_encode($a->deliver(down(),['version'=>1,'channel'=>'webhook','observed_at'=>1001,'evidence_ref'=>'controlbot:alert']),JSON_THROW_ON_ERROR),PHP_EOL;exit;}
if($case==='dedupe'){$a=adapter(fn($d)=>[],fn($p)=>['status'=>'delivered','code'=>'accepted']);$x=$a->deliver(down(),['version'=>1,'channel'=>'webhook','observed_at'=>1001,'evidence_ref'=>'controlbot:alert']);$y=$a->deliver(down(),['version'=>1,'channel'=>'webhook','observed_at'=>1002,'evidence_ref'=>'controlbot:alert']);echo json_encode(['same'=>$x['dedupe_key']===$y['dedupe_key'],'keys'=>array_keys(($x['receipt']??[]))],JSON_THROW_ON_ERROR),PHP_EOL;exit;}
if($case==='pure'){$s=strtolower((string)file_get_contents(__DIR__.'/../src/ExternalMonitorAdapter.php'));$r=strtolower((string)file_get_contents(__DIR__.'/../scripts/external-monitor.php'));$forbidden=['new pdo','mysqli','file_put_contents','shell_exec','proc_open','passthru(','system(','exec('];$hits=[];foreach($forbidden as $n)if(str_contains($s,$n)||str_contains($r,$n))$hits[]=$n;echo json_encode(['hits'=>$hits,'actions'=>str_contains($r,'github_actions')||str_contains($r,'actions/checkout'),'embedded'=>preg_match('/(?:ghp_|github_pat_|sk-[a-z0-9]|password\s*=)/i',$r)===1],JSON_THROW_ON_ERROR),PHP_EOL;exit;}
fwrite(STDERR,"unknown case\n");exit(2);
